apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: saas-api
  labels:
    app.kubernetes.io/name: saas-api
    app.kubernetes.io/component: api
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  ingressClassName: nginx
  rules:
    - host: api.staging.saas-boilerplate.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: saas-api
                port:
                  number: 8000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: saas-app
  labels:
    app.kubernetes.io/name: saas-app
    app.kubernetes.io/component: frontend
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  ingressClassName: nginx
  rules:
    - host: staging.saas-boilerplate.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: saas-app
                port:
                  number: 3000
