apiVersion: v1
kind: Service
metadata:
  name: saas-app
  labels:
    app.kubernetes.io/name: saas-app
    app.kubernetes.io/component: frontend
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: saas-app
  ports:
    - name: http
      port: 3000
      targetPort: http
