apiVersion: v1
kind: Service
metadata:
  name: saas-api
  labels:
    app.kubernetes.io/name: saas-api
    app.kubernetes.io/component: api
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: saas-api
  ports:
    - name: http
      port: 8000
      targetPort: http
