apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: saas-staging
  namespace: argocd
spec:
  project: saas-boilerplate
  source:
    repoURL: https://github.com/Khalil-Bchir/full-stack-saas-boilerplate.git
    targetRevision: staging
    path: deploy/k8s/overlays/staging
  destination:
    server: https://kubernetes.default.svc
    namespace: saas-staging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
