apiVersion: v1
kind: Service
metadata:
  name: saas-ai
  labels:
    app.kubernetes.io/name: saas-ai
    app.kubernetes.io/component: ai
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: saas-ai
  ports:
    - name: http
      port: 5000
      targetPort: http
