apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: saas-boilerplate
  namespace: argocd
spec:
  description: SaaS boilerplate workloads
  sourceRepos:
    - '*'
  destinations:
    - namespace: saas-staging
      server: https://kubernetes.default.svc
    - namespace: saas-production
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: ''
      kind: Namespace
