apiVersion: v1
kind: Service
metadata:
  name: saas-redis
  labels:
    app.kubernetes.io/name: saas-redis
    app.kubernetes.io/component: redis
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: saas-redis
  ports:
    - name: redis
      port: 6379
      targetPort: redis
